threads: 1
# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------
PATHS=config['paths']
DATASET = os.path.splitext(os.path.basename(PATHS["dataset"]))[0]
REPRESENTATIONS = config["representations"]
FOLDS = config["folds"]
ENUM_FACTORS = config["enum_factors"]
OUTPUT_DIR = PATHS['output_dir']
MIN_FREQS = config['structural_prior_min_freq']

shell.executable("/bin/bash")

wildcard_constraints:
    dataset=DATASET,
    repr='|'.join(REPRESENTATIONS),
    fold='\d+'

# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Rules
# -----------------------------------------------------------------------------

include: "Snakefile_data"
