name: Build Package and Test it

on:
  push:
    branches: [master, dev, vb/coverage]
  pull_request:
    branches: [master, dev]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.10'

    - name: Install torch (CPU-only)
      run: pip3 install torch --index-url https://download.pytorch.org/whl/cpu

    - name: Build source
      run: pip install .

    - name: Install developer dependencies
      run: pip install .[dev]

    - name: Pytest
      run: pytest tests/test_snakemake.py
