name: Build Package and Test it

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.10'

    - name: Install torch (CPU-only)
      run: pip3 install torch --index-url https://download.pytorch.org/whl/cpu

    - name: Build source
      run: pip install .

    - name: Install developer dependencies
      run: pip install .[dev]

    - name: Conda Info
      run: |
        conda info
        conda list --export

    - name: Pre-commit checks
      run: |
          pre-commit run --all-files

    - name: Pytest
      shell: bash
      run: pytest tests/test_snakemake.py

    - uses: actions/upload-artifact@v4
      with:
        path: out/
