name: Build Package and Test it

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.10'

    - name: Build source
      run: pip install .

    - name: Install developer dependencies
      run: pip install .[dev]

    - name: Pytest 1
      run: pytest tests/test_nps_generation.py::test_clean_SMILES

    - name: Pytest 2
      run: pytest tests/test_nps_generation.py::test_augment_SMILES

    - name: Pytest 3
      run: pytest tests/test_nps_generation.py::test_train_model

    - name: Pytest 4
      run: pytest tests/test_nps_generation.py::test_calculate_outcomes

    - name: Pytest 5
      run: pytest tests/test_nps_generation.py::test_calculate_outcomes_distribution

    - name: Pytest 6
      run: pytest tests/test_nps_generation.py::test_sample_molecules