name: Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pip dependencies
      run: |
        pip install -r requirements.txt

    - name: Install package
      run: pip install -e . --no-deps

    - name: Pre-commit checks
      run: |
          pre-commit run --all-files

    - name: Pytest with coverage
      run: coverage run --source=src/clm -m pytest

    - name: List dependencies
      run: pip freeze

    - name: Upload coverage to Coveralls
      if: matrix.os == 'ubuntu-latest'
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
