name: Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.10'

    - name: Install torch (CPU-only)
      run: pip3 install torch --index-url https://download.pytorch.org/whl/cpu

    - name: Install package with extras
      run: pip install .[dev]

    - name: Pre-commit checks
      run: |
          pre-commit run --all-files

    - name: Pytest with coverage
      shell: bash
      run: coverage run --source=clm -m pytest

    - name: Upload coverage to Coveralls
      if: matrix.os == 'ubuntu-latest'
      run: coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
